### ISSUE TITLE
Create a blog hosted on github 

### ISSUE THREAD

**Issue by djfnd** [neume-network/website#1]
## Scope

* neume requires somewhere to host external writing about the project
* The initial blog post should be available alongside the rebranding of this Github organisation from musicOS to neume, to provide context around the reasons for the rename and positioning of each project; neume being the future name for the open source data crawling and indexing work, musicOS being the front end application being built by HIFI Labs
* The solution should be something that is easy to push writing out to by the core team and can be addressed through the neume TLD (neume.network)
* [Hexo](https://hexo.io/) has been mentioned as an option for framework, alongside other options such as [Jekyll](https://jekyllrb.com/); other options can also be considered

## Notes

* Discussion on the proposed approach should be conducted within this Issue, through to sign-off from myself (@djfnd) and @reimertz 

## Deliverables

* A functioning blog interface that is hosted within this GitHub, updatable by the team, and publicly accessible

## Deadline

* Go live by 18th May

**Comment by il3ven** [comment]
#### Which framework should we use?

My opinion is that a blog should not be complicated. Even a simple 90s style HTML websites work great as blogs. I love [vitalik's](https://vitalik.ca/) blog. The main requirements are markdown support, good looking, social preview and SEO.

There are many frameworks out there but most feel overkill to me. For me, Hexo seems to sit in the right spot. Note, this is from a quick look. I haven't used it. @timdaub's blog is also made using Hexo and it is great. I have heard no complaints.

[11ty](https://www.11ty.dev/) also looks very cool to me with the same principles as Hexo but even more simpler. ([Demo blog](https://www.11ty.dev/blog/))

I heard @reimertz is suggesting Next.js but I will recommend a better version of Next.js which is more suitable for blogs i.e. Gatsby.js. The https://ethereum.org is made using Gatsby.

In my opinion overkill is an understatement for Next/Gatsby. According to my understanding, we just want a place to host our writings and not create a complete website with multiple types of articles like ethereum.org. If we go with Next/Gatsby then we will have to take care of converting Markdown, social previews, syntax highlighting and I guess theming will also be difficult. It is the tradeoff between easier theming or more control.

#### Do you have a visual of the blog in mind?

**Comment by djfnd** [comment]
I agree, for me the key parameters are simplicity and ease to ship words. Completely agree with your view on vitalik's blog. We should have some artwork to come alongside launch, so visual components should be factored in, but simple and a resistance to overkill are my personal priorities. But would love to hear @reimertz 's thoughts too!

**Comment by TimDaub** [comment]
A few requirementa from my side:

- SEO has to be built-in (I know that some hexo templates have it)
- It must use a programming language we can all write, I'd assume JS being the common denominator

**Comment by il3ven** [comment]
What exactly do you mean by SEO? How to judge if a template has SEO capabilities?

**Comment by TimDaub** [comment]
- By SEO, I mean that the website is optimized to be ideally indexed by e.g. Google. A set of criteria can be found e.g. here: https://developers.google.com/search/docs/beginner/seo-starter-guide
- However, I only have strong opinions on one thing: We outsource SEO to the blog framework, and DON'T do it ourselves. My experience is that I tried doing SEO with rugpullindex.com and it ended up not bringing good results as, e.g. my personal blog with hexo does much better, despite countless hours of SEO. Not having to deal with fixing SEO bugs e.g. through Google Search Engine Console is better.

**Comment by djfnd** [comment]
What are you thinking @reimertz ?

**Comment by reimertz** [comment]
I think you have a lot of great points @il3ven! 

I can see the arguments / points that Next.js is overkill and like your suggestion of going with [11ty](https://www.11ty.dev/) since it seems to be a good compensation between good DX, featureset and future-proofing for adding documentation later etc. But I have no strong opinion. 

On another note, I could assist in setting up Cloudflare CDN + CD/CI using Netlify if you'd like since the DNS is already handled using Cloudflare. 

Do we care about Analytics? I feel pretty strongly about building cookie-less site so going with something like Plausible would be preferable. If so, I could assist in setting up that as well.

**Comment by reimertz** [comment]
And agreed @TimDaub - we shouldn't have to worry about SEO - all the appropriate meta tags should be added automatically by whatever framework we use + sitemap.xml generation. 

I would love if we could have RSS feeds too but that seems more like a nice-to-have  :)

**Comment by il3ven** [comment]
Ok. So, I will start looking into using 11ty. If for some reason I am not able to find a good SEO template then I will switch back to Hexo.

I find github pages and github actions to be simple but if you wanna go with Cloudflare+Netlify then that's your call.

**Comment by reimertz** [comment]
> I find github pages and github actions to be simple but if you wanna go with Cloudflare+Netlify then that's your call

Then please go with github pages and I can point the DNS to that page once we're ready.

**Comment by djfnd** [comment]
> Ok. So, I will start looking into using 11ty. If for some reason I am not able to find a good SEO template then I will switch back to Hexo.
> 
> I find github pages and github actions to be simple but if you wanna go with Cloudflare+Netlify then that's your call.

Great stuff, seems like we're all alligned then. So happy to go forward when you're ready to go @il3ven , based on the above.

**Comment by il3ven** [comment]
For today, I have read about 11ty as I haven't used it before and also shortlisted a template. In my opinion the template is really awesome. It has all the features that we talked about i.e. sitemap, rss, seo, social preview and minimal design.

Tomorrow, I will start working on this template.

Template Demo: https://eleventyduo.netlify.app/
Template Code: https://github.com/yinkakun/eleventy-duo

**Comment by djfnd** [comment]
Perfect!
